package OKNA;

import BAZA.MYSQL_BAZA;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import net.proteanit.sql.DbUtils;

public class DOknoSpisZas extends javax.swing.JDialog {

    /**
     * Creates new form oProgramie
     */
    public DOknoSpisZas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        /*jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"SR", "Szkolenie okresowe BHP dla pracowników zatrudnionych na stanowiskach robotniczych", "SR_ST", "STOMIL"},
                {"ST", "Szkolenie okresowe BHP dla pracowników zatrudnionych na stanowiskach technicznych", "ST_ST", "STOMIL"},
                {"AB", "Szkolenie okresowe BHP dla pracowników administracyjno - biurowych", "AB_ST", "STOMIL"},
                {"ABK", "Szkolenie okresowe BHP dla pracowników administracyjno - biurowych (praca przy komputerze)", "ABK_ST", "STOMIL"},
                {"KP", "Szkolenie okresowe BHP dla osób kierujących pracownikami", "KP_ST", "STOMIL"},
                {"KPB", "Szkolenie okresowe BHP dla pracodawców i osób kierujących prowadzących sprawy BHP", "KPB_ST", "STOMIL"},
                {"OPB", "Szkolenie okresowe z Ochrony przeciwpożarowej dla pracowników zatrudnionych na stanowiskach robotniczych", "OPB_ST", "STOMIL"},
                {"OPA", "Szkolenie okresowe z Ochrony przeciwpożarowej dla pracowników administracyjno - biurowych", "OPA_ST", "STOMIL"},
                {"OPE", "Szkolenie okresowe dla wyznaczonych pracowników z zakresu ochrony przeciwpożarowej - zwalczania pożaru i ewakuacji", "OPE_ST", "STOMIL"},
                {"PPM", "Szkolenie okresowe dla wyznaczonych pracowników z zakresu udzielania pierwszej pomocy medycznej (przedlekarskiej)", "PPM_ST", "STOMIL"},
                {"IBP", "Zapoznanie z Instrukcją Bezpieczeństwa Pożarowego", "IBP_ST", "STOMIL"},
                {"SPA", "Przeszkolenie pracowników na wypadek awarii", "SPA_ST", "STOMIL"},
                {"ZHR", "szkolenie okresowe pracowników zatrudnionych przy załadunku i rozładunku - hakowy", "ZHR_AQ", "AQUANET"},
                {"SRL", "szkolenie okresowe pracowników zatrudnionych na stanowiskach robotniczych – pracownik laboratorium", "SRL_AQ", "AQUANET"},
                {"SRO", "szkolenie okresowe pracowników zatrudnionych na stanowiskach robotniczych – pracownik ochrony", "SRO_AQ", "AQUANET"}
            },
            new String [] {
                "KOD", "OPIS", "PRZYKŁAD","FIRMA"
            }
        )
        
        );
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(0).setMinWidth(50);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(50);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(70);
        jTable1.getColumnModel().getColumn(2).setMinWidth(70);
        jTable1.getColumnModel().getColumn(2).setMaxWidth(70);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(70);
        jTable1.getColumnModel().getColumn(3).setMinWidth(70);
        jTable1.getColumnModel().getColumn(3).setMaxWidth(70);
        jTable1.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        jTable1.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
        jTable1.getColumnModel().getColumn(2).setCellRenderer( centerRenderer );
        jTable1.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Spis dostępnych zaświadczeń");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(224, 224, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setToolTipText("");
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // jTable1.setModel(DbUtils.resultSetToTableModel(MYSQL_BAZA.selectFirma(CONF.firma_domyslna)));
        jTable1.setModel(DbUtils.resultSetToTableModel(MYSQL_BAZA.widokWzory()));
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(0).setMinWidth(60);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(60);
        jTable1.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        jTable1.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DOknoSpisZas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DOknoSpisZas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DOknoSpisZas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DOknoSpisZas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DOknoSpisZas dialog = new DOknoSpisZas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
